{{- if .Values.ingresses -}}
{{- $fullName := include "sftp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: v1
kind: List
items:
  {{- range .Values.ingresses }}
    kind: Ingress
    metadata:
      name: {{ .name }}
      labels:
        {{- include "sftp.labels" . | nindent 4 }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 4 }}
      {{- end }}
    spec:
      {{- if .tls }}
      tls:
        {{- range .tls }}
        - hosts:
            {{- range .hosts }}
            - {{ . | quote }}
            {{- end }}
          secretName: {{ .secretName }}
        {{- end }}
      {{- end }}
      rules:
        {{- range .hosts }}
        - host: {{ .host | quote }}
          http:
            paths:
              {{- range .paths }}
              - path: {{ . }}
                backend:
                  serviceName: {{ $fullName }}
                  servicePort: {{ $svcPort }}
              {{- end }}
        {{- end }}
  {{- end }}
{{- end }}