apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if ne .Values.service.type "NodePort" }}
{{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "sftp.selectorLabels" . | nindent 4 }}

{{- if .Values.extraServices -}}
apiVersion: v1
kind: List
items:
  {{- range .Values.extraServices }}
    kind: Service
    metadata:
        name: {{ .name }}
        labels:
            {{- include "sftp.labels" . | nindent 4 }}
        {{- with .annotations }}
        annotations:
            {{- toYaml . | nindent 4 }}
        {{- end }}
    spec:
        {{- if ne .type "NodePort" }}
        {{- if .clusterIP }}
        clusterIP: "{{ .clusterIP }}"
        {{- end }}
        {{- end }}
        {{- if .externalIPs }}
        externalIPs:
        {{ toYaml .externalIPs | indent 4 }}
        {{- end }}
        {{- if .loadBalancerIP }}
        loadBalancerIP: "{{ .loadBalancerIP }}"
        {{- end }}
        {{- if .loadBalancerSourceRanges }}
        loadBalancerSourceRanges:
        {{ toYaml .loadBalancerSourceRanges | indent 4 }}
        {{- end }}
        {{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.externalTrafficPolicy) }}
        externalTrafficPolicy: "{{ .externalTrafficPolicy }}"
        {{- end }}
        type: {{ .type }}
        ports:
            - port: {{ .port }}
            targetPort: ssh
            protocol: TCP
            name: ssh
        selector:
            {{- include "sftp.selectorLabels" . | nindent 4 }}
    {{- end }}
{{- end }}